// Package refyne provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package refyne

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AnalyzeInputBodyFetchMode.
const (
	AnalyzeInputBodyFetchModeAuto    AnalyzeInputBodyFetchMode = "auto"
	AnalyzeInputBodyFetchModeDynamic AnalyzeInputBodyFetchMode = "dynamic"
	AnalyzeInputBodyFetchModeStatic  AnalyzeInputBodyFetchMode = "static"
)

// Defines values for CleanerOptionsInputOutput.
const (
	Html     CleanerOptionsInputOutput = "html"
	Markdown CleanerOptionsInputOutput = "markdown"
	Text     CleanerOptionsInputOutput = "text"
)

// Defines values for CleanerOptionsInputPreset.
const (
	Aggressive CleanerOptionsInputPreset = "aggressive"
	Default    CleanerOptionsInputPreset = "default"
	Minimal    CleanerOptionsInputPreset = "minimal"
)

// Defines values for CrawlOptionsFetchMode.
const (
	CrawlOptionsFetchModeAuto    CrawlOptionsFetchMode = "auto"
	CrawlOptionsFetchModeDynamic CrawlOptionsFetchMode = "dynamic"
	CrawlOptionsFetchModeStatic  CrawlOptionsFetchMode = "static"
)

// Defines values for CreateSavedSiteInputBodyFetchMode.
const (
	CreateSavedSiteInputBodyFetchModeAuto    CreateSavedSiteInputBodyFetchMode = "auto"
	CreateSavedSiteInputBodyFetchModeDynamic CreateSavedSiteInputBodyFetchMode = "dynamic"
	CreateSavedSiteInputBodyFetchModeStatic  CreateSavedSiteInputBodyFetchMode = "static"
)

// Defines values for CreateSchemaInputBodyVisibility.
const (
	CreateSchemaInputBodyVisibilityPrivate CreateSchemaInputBodyVisibility = "private"
	CreateSchemaInputBodyVisibilityPublic  CreateSchemaInputBodyVisibility = "public"
)

// Defines values for ExtractInputBodyFetchMode.
const (
	ExtractInputBodyFetchModeAuto    ExtractInputBodyFetchMode = "auto"
	ExtractInputBodyFetchModeDynamic ExtractInputBodyFetchMode = "dynamic"
	ExtractInputBodyFetchModeStatic  ExtractInputBodyFetchMode = "static"
)

// Defines values for LLMConfigInputProvider.
const (
	Anthropic  LLMConfigInputProvider = "anthropic"
	Credits    LLMConfigInputProvider = "credits"
	Helicone   LLMConfigInputProvider = "helicone"
	Ollama     LLMConfigInputProvider = "ollama"
	Openai     LLMConfigInputProvider = "openai"
	Openrouter LLMConfigInputProvider = "openrouter"
)

// Defines values for UpdateSavedSiteInputBodyFetchMode.
const (
	Auto    UpdateSavedSiteInputBodyFetchMode = "auto"
	Dynamic UpdateSavedSiteInputBodyFetchMode = "dynamic"
	Static  UpdateSavedSiteInputBodyFetchMode = "static"
)

// Defines values for UpdateSchemaInputBodyVisibility.
const (
	UpdateSchemaInputBodyVisibilityPrivate UpdateSchemaInputBodyVisibility = "private"
	UpdateSchemaInputBodyVisibilityPublic  UpdateSchemaInputBodyVisibility = "public"
)

// Defines values for GetJobResultsRawParamsFormat.
const (
	Json  GetJobResultsRawParamsFormat = "json"
	Jsonl GetJobResultsRawParamsFormat = "jsonl"
	Yaml  GetJobResultsRawParamsFormat = "yaml"
)

// Defines values for GetUsageParamsPeriod.
const (
	Day   GetUsageParamsPeriod = "day"
	Month GetUsageParamsPeriod = "month"
	Week  GetUsageParamsPeriod = "week"
	Year  GetUsageParamsPeriod = "year"
)

// APIKeyResponse defines model for APIKeyResponse.
type APIKeyResponse struct {
	CreatedAt  string    `json:"created_at"`
	ExpiresAt  *string   `json:"expires_at,omitempty"`
	Id         string    `json:"id"`
	KeyPrefix  string    `json:"key_prefix"`
	LastUsedAt *string   `json:"last_used_at,omitempty"`
	Name       string    `json:"name"`
	Scopes     *[]string `json:"scopes"`
}

// AdminJobResultsOutputBody defines model for AdminJobResultsOutputBody.
type AdminJobResultsOutputBody struct {
	// DownloadUrl Presigned URL to download results (valid for 1 hour)
	DownloadUrl string `json:"download_url"`

	// ExpiresAt URL expiration time
	ExpiresAt string `json:"expires_at"`

	// JobId Job ID
	JobId string `json:"job_id"`
}

// AnalysisResultInput defines model for AnalysisResultInput.
type AnalysisResultInput struct {
	// DetectedElements Detected data elements
	DetectedElements *[]DetectedElementInput `json:"detected_elements"`

	// FollowPatterns Follow patterns
	FollowPatterns *[]FollowPatternInput `json:"follow_patterns"`

	// PageType Detected page type
	PageType *string `json:"page_type,omitempty"`

	// RecommendedFetchMode Recommended fetch mode
	RecommendedFetchMode *string `json:"recommended_fetch_mode,omitempty"`

	// SampleLinks Sample links found
	SampleLinks *[]string `json:"sample_links"`

	// SiteSummary Brief site description
	SiteSummary *string `json:"site_summary,omitempty"`

	// SuggestedSchema Schema (JSON or YAML format)
	SuggestedSchema *string `json:"suggested_schema,omitempty"`
}

// AnalysisResultOutput defines model for AnalysisResultOutput.
type AnalysisResultOutput struct {
	// DetectedElements Detected data elements
	DetectedElements *[]DetectedElementOutput `json:"detected_elements"`

	// FollowPatterns Follow patterns
	FollowPatterns *[]FollowPatternOutput `json:"follow_patterns"`

	// PageType Detected page type
	PageType string `json:"page_type"`

	// RecommendedFetchMode Recommended fetch mode
	RecommendedFetchMode string `json:"recommended_fetch_mode"`

	// SampleLinks Sample links found
	SampleLinks *[]string `json:"sample_links"`

	// SiteSummary Brief site description
	SiteSummary string `json:"site_summary"`

	// SuggestedSchema Schema suggestion (JSON format)
	SuggestedSchema string `json:"suggested_schema"`
}

// AnalyticsJobResponse defines model for AnalyticsJobResponse.
type AnalyticsJobResponse struct {
	CompletedAt     *string `json:"completed_at,omitempty"`
	CostUsd         float64 `json:"cost_usd"`
	CreatedAt       string  `json:"created_at"`
	DiscoveryMethod *string `json:"discovery_method,omitempty"`
	ErrorCategory   *string `json:"error_category,omitempty"`
	ErrorMessage    *string `json:"error_message,omitempty"`
	Id              string  `json:"id"`
	IsByok          bool    `json:"is_byok"`
	LlmCostUsd      float64 `json:"llm_cost_usd"`
	Model           *string `json:"model,omitempty"`
	Provider        *string `json:"provider,omitempty"`
	Status          string  `json:"status"`
	TokensInput     int64   `json:"tokens_input"`
	TokensOutput    int64   `json:"tokens_output"`
	Type            string  `json:"type"`
	Url             string  `json:"url"`
	UserId          string  `json:"user_id"`
}

// AnalyzeInputBody defines model for AnalyzeInputBody.
type AnalyzeInputBody struct {
	// CaptureDebug Enable debug capture to store raw LLM request/response for troubleshooting. Defaults to true for analyze jobs.
	CaptureDebug *bool `json:"capture_debug,omitempty"`

	// Depth Crawl depth: 0=single page, 1=one level deep
	Depth *int64 `json:"depth,omitempty"`

	// FetchMode Fetch mode: auto, static, or dynamic
	FetchMode *AnalyzeInputBodyFetchMode `json:"fetch_mode,omitempty"`

	// Url URL to analyze
	Url string `json:"url"`
}

// AnalyzeInputBodyFetchMode Fetch mode: auto, static, or dynamic
type AnalyzeInputBodyFetchMode string

// AnalyzeResponseBody defines model for AnalyzeResponseBody.
type AnalyzeResponseBody struct {
	// DetectedElements Data elements detected on the page
	DetectedElements *[]DetectedElementOutput `json:"detected_elements"`

	// FollowPatterns URL/selector patterns for crawling
	FollowPatterns *[]FollowPatternOutput `json:"follow_patterns"`

	// JobId Unique job ID for this analysis (for tracking/history)
	JobId string `json:"job_id"`

	// PageType Detected page type: listing, detail, article, product, recipe, unknown
	PageType string `json:"page_type"`

	// RecommendedFetchMode Recommended fetch mode: static or dynamic
	RecommendedFetchMode string `json:"recommended_fetch_mode"`

	// SampleData Optional preview extraction result
	SampleData interface{} `json:"sample_data,omitempty"`

	// SampleLinks Sample links found on the page
	SampleLinks *[]string `json:"sample_links"`

	// SiteSummary Brief description of what the site/page is about
	SiteSummary string `json:"site_summary"`

	// SuggestedSchema Schema suggestion for extraction (JSON format)
	SuggestedSchema string `json:"suggested_schema"`
}

// CleanerChainItemResponse defines model for CleanerChainItemResponse.
type CleanerChainItemResponse struct {
	// Name Cleaner name
	Name string `json:"name"`
}

// CleanerConfigInput defines model for CleanerConfigInput.
type CleanerConfigInput struct {
	// Name Cleaner name (noop, refyne)
	Name    string               `json:"name"`
	Options *CleanerOptionsInput `json:"options,omitempty"`
}

// CleanerOptionResponse defines model for CleanerOptionResponse.
type CleanerOptionResponse struct {
	// Default Default value if not specified
	Default interface{} `json:"default"`

	// Description Description of what this option does
	Description string `json:"description"`

	// Name Option name (e.g., 'output', 'tables')
	Name string `json:"name"`

	// Type Option type (string, boolean)
	Type string `json:"type"`
}

// CleanerOptionsInput defines model for CleanerOptionsInput.
type CleanerOptionsInput struct {
	// BaseUrl Base URL for resolving relative links
	BaseUrl *string `json:"base_url,omitempty"`

	// ExtractHeadings Extract heading structure to frontmatter (markdown)
	ExtractHeadings *bool `json:"extract_headings,omitempty"`

	// ExtractImages Extract images to frontmatter with {{IMG_001}} placeholders (markdown)
	ExtractImages *bool `json:"extract_images,omitempty"`

	// IncludeFrontmatter Prepend YAML frontmatter with metadata (markdown output)
	IncludeFrontmatter *bool `json:"include_frontmatter,omitempty"`

	// KeepSelectors CSS selectors for elements to always keep
	KeepSelectors *[]string `json:"keep_selectors"`

	// Output Output format: html, text, or markdown
	Output *CleanerOptionsInputOutput `json:"output,omitempty"`

	// Preset Preset: default, minimal, or aggressive
	Preset *CleanerOptionsInputPreset `json:"preset,omitempty"`

	// RemoveSelectors CSS selectors for elements to remove
	RemoveSelectors *[]string `json:"remove_selectors"`

	// ResolveUrls Resolve relative URLs to absolute using base_url
	ResolveUrls *bool `json:"resolve_urls,omitempty"`
}

// CleanerOptionsInputOutput Output format: html, text, or markdown
type CleanerOptionsInputOutput string

// CleanerOptionsInputPreset Preset: default, minimal, or aggressive
type CleanerOptionsInputPreset string

// CleanerResponse defines model for CleanerResponse.
type CleanerResponse struct {
	// Description Description of what this cleaner does
	Description string `json:"description"`

	// Name Cleaner name to use in cleaner_chain
	Name string `json:"name"`

	// Options Available options for this cleaner
	Options *[]CleanerOptionResponse `json:"options"`
}

// CrawlJobResponseBody defines model for CrawlJobResponseBody.
type CrawlJobResponseBody struct {
	// CostUsd Total USD cost charged (sync mode)
	CostUsd *float64 `json:"cost_usd,omitempty"`

	// Data Merged extraction results from all pages (sync mode, completed only)
	Data *map[string]interface{} `json:"data,omitempty"`

	// DurationMs Total job duration in milliseconds (sync mode)
	DurationMs *int64 `json:"duration_ms,omitempty"`

	// ErrorMessage Error message if job failed or timed out
	ErrorMessage *string `json:"error_message,omitempty"`

	// JobId Unique job identifier (ULID)
	JobId string `json:"job_id"`

	// PageCount Number of pages successfully extracted (sync mode)
	PageCount *int64 `json:"page_count,omitempty"`

	// QueuePosition Position in queue (1-indexed, only for pending jobs)
	QueuePosition *int64 `json:"queue_position,omitempty"`

	// Status Job status: pending, running, completed, failed
	Status string `json:"status"`

	// StatusUrl URL to poll for job status (async mode)
	StatusUrl  *string     `json:"status_url,omitempty"`
	TokenUsage *TokenUsage `json:"token_usage,omitempty"`
}

// CrawlMapEntry defines model for CrawlMapEntry.
type CrawlMapEntry struct {
	// CompletedAt When processing completed
	CompletedAt *string `json:"completed_at,omitempty"`

	// Depth Crawl depth (0 for seed URL)
	Depth int64 `json:"depth"`

	// DiscoveredAt When URL was discovered
	DiscoveredAt *string `json:"discovered_at,omitempty"`

	// ErrorCategory Error classification: rate_limit, quota_exceeded, provider_error, invalid_key, context_length, invalid_response, network_error, unknown
	ErrorCategory *string `json:"error_category,omitempty"`

	// ErrorDetails Full error details (BYOK users only)
	ErrorDetails *string `json:"error_details,omitempty"`

	// ErrorMessage Error message if failed
	ErrorMessage *string `json:"error_message,omitempty"`

	// ExtractDurationMs Time to extract data in ms
	ExtractDurationMs int64 `json:"extract_duration_ms"`

	// FetchDurationMs Time to fetch page in ms
	FetchDurationMs int64 `json:"fetch_duration_ms"`

	// Id Result ID
	Id string `json:"id"`

	// LlmModel LLM model used (BYOK users only)
	LlmModel *string `json:"llm_model,omitempty"`

	// LlmProvider LLM provider used (BYOK users only)
	LlmProvider *string `json:"llm_provider,omitempty"`

	// ParentUrl URL that discovered this page (null for seed)
	ParentUrl *string `json:"parent_url,omitempty"`

	// Status Crawl status: pending, crawling, completed, failed, skipped
	Status string `json:"status"`

	// TokenUsageInput Input tokens used
	TokenUsageInput int64 `json:"token_usage_input"`

	// TokenUsageOutput Output tokens used
	TokenUsageOutput int64 `json:"token_usage_output"`

	// Url Page URL
	Url string `json:"url"`
}

// CrawlOptions defines model for CrawlOptions.
type CrawlOptions struct {
	// Concurrency Concurrent extraction requests per job
	Concurrency *int64 `json:"concurrency,omitempty"`

	// Delay Delay between requests (e.g., 500ms, 1s, 2s)
	Delay *string `json:"delay,omitempty"`

	// ExtractFromSeeds Extract data from the seed URL (not just discovered pages)
	ExtractFromSeeds *bool `json:"extract_from_seeds,omitempty"`

	// FetchMode Page fetching mode: auto (detect and retry with browser if needed), static (fast, Colly-based), dynamic (browser rendering for JS-heavy sites, requires content_dynamic feature)
	FetchMode *CrawlOptionsFetchMode `json:"fetch_mode,omitempty"`

	// FollowPattern Regex pattern to filter URLs. Only matching URLs are crawled.
	FollowPattern *string `json:"follow_pattern,omitempty"`

	// FollowSelector CSS selector(s) for links to follow. Comma-separated or newline-separated.
	FollowSelector *string `json:"follow_selector,omitempty"`

	// MaxDepth Maximum crawl depth from seed URL (1 = seed + direct links)
	MaxDepth *int64 `json:"max_depth,omitempty"`

	// MaxPages Maximum total pages to crawl (0 = no limit, up to tier max)
	MaxPages *int64 `json:"max_pages,omitempty"`

	// MaxUrls Maximum URLs to discover and queue
	MaxUrls *int64 `json:"max_urls,omitempty"`

	// NextSelector CSS selector for pagination 'next' link
	NextSelector *string `json:"next_selector,omitempty"`

	// SameDomainOnly Only follow links on the same domain as seed URL
	SameDomainOnly *bool `json:"same_domain_only,omitempty"`

	// UseSitemap Discover URLs from sitemap.xml instead of CSS selectors
	UseSitemap *bool `json:"use_sitemap,omitempty"`
}

// CrawlOptionsFetchMode Page fetching mode: auto (detect and retry with browser if needed), static (fast, Colly-based), dynamic (browser rendering for JS-heavy sites, requires content_dynamic feature)
type CrawlOptionsFetchMode string

// CrawlOptionsInput defines model for CrawlOptionsInput.
type CrawlOptionsInput struct {
	// FollowPattern Regex pattern for URLs to filter
	FollowPattern *string `json:"follow_pattern,omitempty"`

	// FollowSelector CSS selector for links to follow
	FollowSelector *string `json:"follow_selector,omitempty"`

	// MaxDepth Max crawl depth
	MaxDepth *int64 `json:"max_depth,omitempty"`

	// MaxPages Max pages (0 = no limit)
	MaxPages *int64 `json:"max_pages,omitempty"`
}

// CrawlOptionsOutput defines model for CrawlOptionsOutput.
type CrawlOptionsOutput struct {
	// FollowPattern Regex pattern for URLs to filter
	FollowPattern *string `json:"follow_pattern,omitempty"`

	// FollowSelector CSS selector for links to follow
	FollowSelector *string `json:"follow_selector,omitempty"`

	// MaxDepth Max crawl depth
	MaxDepth *int64 `json:"max_depth,omitempty"`

	// MaxPages Max pages (0 = no limit)
	MaxPages *int64 `json:"max_pages,omitempty"`
}

// CreateCrawlJobInputBody defines model for CreateCrawlJobInputBody.
type CreateCrawlJobInputBody struct {
	// CaptureDebug Enable debug capture to store raw LLM request/response for troubleshooting
	CaptureDebug *bool `json:"capture_debug,omitempty"`

	// CleanerChain Content cleaner chain (default: [markdown])
	CleanerChain *[]CleanerConfigInput `json:"cleaner_chain"`
	LlmConfig    *LLMConfigInput       `json:"llm_config,omitempty"`
	Options      *CrawlOptions         `json:"options,omitempty"`

	// Schema Extraction instructions - either a structured schema (YAML/JSON with 'name' and 'fields') or freeform natural language prompt. The API auto-detects the format.
	Schema interface{} `json:"schema"`

	// Url Seed URL to start crawling from
	Url     string              `json:"url"`
	Webhook *InlineWebhookInput `json:"webhook,omitempty"`

	// WebhookId ID of a saved webhook to call on job events
	WebhookId *string `json:"webhook_id,omitempty"`

	// WebhookUrl Simple webhook URL (backward compatible)
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// CreateKeyInputBody defines model for CreateKeyInputBody.
type CreateKeyInputBody struct {
	// ExpiresAt Expiration date (RFC3339)
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Name Descriptive name for the key
	Name string `json:"name"`

	// Scopes Permitted scopes (extract, crawl, jobs)
	Scopes *[]string `json:"scopes"`
}

// CreateKeyOutputBody defines model for CreateKeyOutputBody.
type CreateKeyOutputBody struct {
	CreatedAt string  `json:"created_at"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	Id        string  `json:"id"`

	// Key Full API key - only shown once!
	Key       string    `json:"key"`
	KeyPrefix string    `json:"key_prefix"`
	Name      string    `json:"name"`
	Scopes    *[]string `json:"scopes"`
}

// CreatePlatformSchemaInputBody defines model for CreatePlatformSchemaInputBody.
type CreatePlatformSchemaInputBody struct {
	// Category Schema category
	Category string `json:"category"`

	// Description Schema description
	Description *string `json:"description,omitempty"`

	// Name Schema name
	Name string `json:"name"`

	// SchemaYaml YAML schema content
	SchemaYaml string `json:"schema_yaml"`

	// Tags Schema tags
	Tags *[]string `json:"tags"`
}

// CreateSavedSiteInputBody defines model for CreateSavedSiteInputBody.
type CreateSavedSiteInputBody struct {
	AnalysisResult *AnalysisResultInput `json:"analysis_result,omitempty"`
	CrawlOptions   *CrawlOptionsInput   `json:"crawl_options,omitempty"`

	// DefaultSchemaId Default schema ID
	DefaultSchemaId *string `json:"default_schema_id,omitempty"`

	// FetchMode Fetch mode
	FetchMode *CreateSavedSiteInputBodyFetchMode `json:"fetch_mode,omitempty"`

	// Name User-friendly name
	Name *string `json:"name,omitempty"`

	// Url Site URL
	Url string `json:"url"`
}

// CreateSavedSiteInputBodyFetchMode Fetch mode
type CreateSavedSiteInputBodyFetchMode string

// CreateSchemaInputBody defines model for CreateSchemaInputBody.
type CreateSchemaInputBody struct {
	// Category Schema category
	Category *string `json:"category,omitempty"`

	// Description Schema description
	Description *string `json:"description,omitempty"`

	// Name Schema name
	Name string `json:"name"`

	// SchemaYaml YAML schema content
	SchemaYaml string `json:"schema_yaml"`

	// Tags Schema tags
	Tags *[]string `json:"tags"`

	// Visibility Schema visibility
	Visibility CreateSchemaInputBodyVisibility `json:"visibility"`
}

// CreateSchemaInputBodyVisibility Schema visibility
type CreateSchemaInputBodyVisibility string

// DebugCaptureEntry defines model for DebugCaptureEntry.
type DebugCaptureEntry struct {
	// ApiVersion API version that processed this request
	ApiVersion *string `json:"api_version,omitempty"`

	// Id Capture ID
	Id string `json:"id"`

	// IsByok Whether user's own API key was used
	IsByok *bool `json:"is_byok,omitempty"`

	// JobType Job type (analyze, extract, crawl)
	JobType  string                  `json:"job_type"`
	Request  DebugCaptureLLMRequest  `json:"request"`
	Response DebugCaptureLLMResponse `json:"response"`

	// Sequence Order within job (0-indexed)
	Sequence *int64 `json:"sequence,omitempty"`

	// Timestamp When the request was made
	Timestamp string `json:"timestamp"`

	// Url Page URL being processed
	Url string `json:"url"`
}

// DebugCaptureLLMRequest defines model for DebugCaptureLLMRequest.
type DebugCaptureLLMRequest struct {
	// ContentSize Size of content sent to LLM
	ContentSize int64 `json:"content_size"`

	// FallbackPosition Position in fallback chain (0=primary)
	FallbackPosition *int64 `json:"fallback_position,omitempty"`

	// FetchMode Content fetch mode
	FetchMode *string `json:"fetch_mode,omitempty"`

	// HintsApplied Preprocessing hints applied
	HintsApplied *map[string]string `json:"hints_applied,omitempty"`

	// IsRetry Whether this was a retry attempt
	IsRetry *bool `json:"is_retry,omitempty"`

	// JsonMode Whether JSON mode was enabled
	JsonMode *bool `json:"json_mode,omitempty"`

	// MaxTokens Max tokens requested
	MaxTokens *int64 `json:"max_tokens,omitempty"`

	// Model LLM model used
	Model string `json:"model"`

	// PageContent Cleaned page content sent to LLM
	PageContent *string `json:"page_content,omitempty"`

	// Prompt Full prompt sent to LLM (for analyze jobs)
	Prompt *string `json:"prompt,omitempty"`

	// PromptSize Total prompt size including system instructions
	PromptSize int64 `json:"prompt_size"`

	// Provider LLM provider used
	Provider string `json:"provider"`

	// Schema Schema used for extraction
	Schema *string `json:"schema,omitempty"`

	// SystemPrompt System instructions sent to LLM
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Temperature Temperature setting
	Temperature *float64 `json:"temperature,omitempty"`

	// UserPrompt Formatted user content/prompt
	UserPrompt *string `json:"user_prompt,omitempty"`
}

// DebugCaptureLLMResponse defines model for DebugCaptureLLMResponse.
type DebugCaptureLLMResponse struct {
	// CostUsd Cost of this request in USD
	CostUsd *float64 `json:"cost_usd,omitempty"`

	// DurationMs Request duration in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// Error Error message if failed
	Error *string `json:"error,omitempty"`

	// ErrorCategory Error classification
	ErrorCategory *string `json:"error_category,omitempty"`

	// InputTokens Input tokens consumed
	InputTokens int64 `json:"input_tokens"`

	// OutputTokens Output tokens generated
	OutputTokens int64 `json:"output_tokens"`

	// ParseError Error if JSON parsing failed
	ParseError *string `json:"parse_error,omitempty"`

	// ParsedOutput Structured data (if successfully parsed)
	ParsedOutput interface{} `json:"parsed_output,omitempty"`

	// RawOutput Raw LLM response text
	RawOutput *string `json:"raw_output,omitempty"`

	// Success Whether the request succeeded
	Success bool `json:"success"`
}

// DeleteSavedSiteOutputBody defines model for DeleteSavedSiteOutputBody.
type DeleteSavedSiteOutputBody struct {
	// Success Whether deletion was successful
	Success bool `json:"success"`
}

// DeleteSchemaOutputBody defines model for DeleteSchemaOutputBody.
type DeleteSchemaOutputBody struct {
	// Success Whether deletion was successful
	Success bool `json:"success"`
}

// DeleteServiceKeyOutputBody defines model for DeleteServiceKeyOutputBody.
type DeleteServiceKeyOutputBody struct {
	Success bool `json:"success"`
}

// DeleteUserServiceKeyOutputBody defines model for DeleteUserServiceKeyOutputBody.
type DeleteUserServiceKeyOutputBody struct {
	Success bool `json:"success"`
}

// DeleteWebhookOutputBody defines model for DeleteWebhookOutputBody.
type DeleteWebhookOutputBody struct {
	// Success Whether deletion was successful
	Success bool `json:"success"`
}

// DetectedElementInput defines model for DetectedElementInput.
type DetectedElementInput struct {
	// Count Element count
	Count *int64 `json:"count,omitempty"`

	// Description Element description
	Description *string `json:"description,omitempty"`

	// Name Element name
	Name *string `json:"name,omitempty"`

	// Type Element type
	Type *string `json:"type,omitempty"`
}

// DetectedElementOutput defines model for DetectedElementOutput.
type DetectedElementOutput struct {
	// Count Number of occurrences
	Count *int64 `json:"count,omitempty"`

	// Description What this element represents
	Description string `json:"description"`

	// Name Suggested field name
	Name string `json:"name"`

	// Type Data type: string, number, boolean, array, url, date
	Type string `json:"type"`
}

// DownloadJobDebugCaptureOutputBody defines model for DownloadJobDebugCaptureOutputBody.
type DownloadJobDebugCaptureOutputBody struct {
	// DownloadUrl Signed URL for downloading the debug capture file
	DownloadUrl string `json:"download_url"`

	// ExpiresAt When the download URL expires
	ExpiresAt string `json:"expires_at"`

	// Filename Suggested filename for the download
	Filename string `json:"filename"`

	// JobId Job ID
	JobId string `json:"job_id"`
}

// ErrorCategoryResponse defines model for ErrorCategoryResponse.
type ErrorCategoryResponse struct {
	Category       string    `json:"category"`
	Count          int64     `json:"count"`
	Percentage     float64   `json:"percentage"`
	SampleMessages *[]string `json:"sample_messages"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// ErrorSummary defines model for ErrorSummary.
type ErrorSummary struct {
	// ByCategory Count of errors by category (rate_limit, quota_exceeded, etc.)
	ByCategory map[string]int64 `json:"by_category"`

	// HasRateLimit True if any rate_limit errors occurred
	HasRateLimit bool `json:"has_rate_limit"`

	// Total Total number of failed pages
	Total int64 `json:"total"`
}

// ExtractInputBody defines model for ExtractInputBody.
type ExtractInputBody struct {
	// CaptureDebug Enable debug capture to store raw LLM request/response for troubleshooting
	CaptureDebug *bool `json:"capture_debug,omitempty"`

	// CleanerChain Content cleaner chain (default: [markdown])
	CleanerChain *[]CleanerConfigInput `json:"cleaner_chain"`

	// FetchMode Fetch mode: auto, static, or dynamic
	FetchMode *ExtractInputBodyFetchMode `json:"fetch_mode,omitempty"`
	LlmConfig *LLMConfigInput            `json:"llm_config,omitempty"`

	// Schema Extraction instructions - either a structured schema (YAML/JSON with 'name' and 'fields') or freeform natural language prompt. The API auto-detects the format and returns 'input_format' in the response.
	Schema interface{} `json:"schema"`

	// Url URL to extract data from
	Url     string              `json:"url"`
	Webhook *InlineWebhookInput `json:"webhook,omitempty"`

	// WebhookId ID of a saved webhook to call on completion
	WebhookId *string `json:"webhook_id,omitempty"`

	// WebhookUrl Simple webhook URL (backward compatible)
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// ExtractInputBodyFetchMode Fetch mode: auto, static, or dynamic
type ExtractInputBodyFetchMode string

// ExtractOutputBody defines model for ExtractOutputBody.
type ExtractOutputBody struct {
	// Data Extracted data matching the schema
	Data interface{} `json:"data"`

	// FetchedAt Timestamp when the page was fetched
	FetchedAt string `json:"fetched_at"`

	// InputFormat How the input was interpreted: 'schema' (structured YAML/JSON) or 'prompt' (freeform text)
	InputFormat string `json:"input_format"`

	// JobId Job ID for this extraction (for history/tracking)
	JobId    string           `json:"job_id"`
	Metadata MetadataResponse `json:"metadata"`

	// Url URL that was extracted
	Url   string        `json:"url"`
	Usage UsageResponse `json:"usage"`
}

// FailingURLResponse defines model for FailingURLResponse.
type FailingURLResponse struct {
	Count int64  `json:"count"`
	Url   string `json:"url"`
}

// FallbackChainEntryInput defines model for FallbackChainEntryInput.
type FallbackChainEntryInput struct {
	// IsEnabled Whether this entry is enabled
	IsEnabled bool `json:"is_enabled"`

	// MaxTokens Max output tokens (nil for default)
	MaxTokens *int64 `json:"max_tokens,omitempty"`

	// Model Model identifier
	Model string `json:"model"`

	// Provider LLM provider name (see /llm/providers for available options)
	Provider string `json:"provider"`

	// Temperature Temperature setting (0.0-1.0, nil for default)
	Temperature *float64 `json:"temperature,omitempty"`
}

// FallbackChainEntryResponse defines model for FallbackChainEntryResponse.
type FallbackChainEntryResponse struct {
	CreatedAt   string   `json:"created_at"`
	Id          string   `json:"id"`
	IsEnabled   bool     `json:"is_enabled"`
	MaxTokens   *int64   `json:"max_tokens,omitempty"`
	Model       string   `json:"model"`
	Position    int64    `json:"position"`
	Provider    string   `json:"provider"`
	Temperature *float64 `json:"temperature,omitempty"`
	Tier        *string  `json:"tier,omitempty"`
	UpdatedAt   string   `json:"updated_at"`
}

// FollowPatternInput defines model for FollowPatternInput.
type FollowPatternInput struct {
	// Description Pattern description
	Description *string `json:"description,omitempty"`

	// Pattern URL pattern
	Pattern *string `json:"pattern,omitempty"`

	// SampleUrls Sample matching URLs
	SampleUrls *[]string `json:"sample_urls"`
}

// FollowPatternOutput defines model for FollowPatternOutput.
type FollowPatternOutput struct {
	// Description What this pattern targets
	Description string `json:"description"`

	// Pattern CSS selector or URL pattern
	Pattern string `json:"pattern"`

	// SampleUrls Example URLs matching this pattern
	SampleUrls *[]string `json:"sample_urls"`
}

// GetAnalyticsJobsOutputBody defines model for GetAnalyticsJobsOutputBody.
type GetAnalyticsJobsOutputBody struct {
	Jobs       *[]AnalyticsJobResponse `json:"jobs"`
	TotalCount int64                   `json:"total_count"`
}

// GetAnalyticsUsersOutputBody defines model for GetAnalyticsUsersOutputBody.
type GetAnalyticsUsersOutputBody struct {
	TotalCount int64                  `json:"total_count"`
	Users      *[]UserSummaryResponse `json:"users"`
}

// GetCrawlMapOutputBody defines model for GetCrawlMapOutputBody.
type GetCrawlMapOutputBody struct {
	// Completed Number of successfully completed pages
	Completed int64 `json:"completed"`

	// Entries Crawl map entries ordered by depth
	Entries      *[]CrawlMapEntry `json:"entries"`
	ErrorSummary *ErrorSummary    `json:"error_summary,omitempty"`

	// Failed Number of failed pages
	Failed int64 `json:"failed"`

	// JobId Job ID
	JobId string `json:"job_id"`

	// MaxDepth Maximum depth reached
	MaxDepth int64 `json:"max_depth"`

	// SeedUrl Initial seed URL
	SeedUrl string `json:"seed_url"`

	// Total Total pages in crawl map
	Total int64 `json:"total"`
}

// GetErrorsOutputBody defines model for GetErrorsOutputBody.
type GetErrorsOutputBody struct {
	ByCategory     *[]ErrorCategoryResponse `json:"by_category"`
	ByProvider     *[]ProviderErrorResponse `json:"by_provider"`
	TopFailingUrls *[]FailingURLResponse    `json:"top_failing_urls"`
}

// GetFallbackChainOutputBody defines model for GetFallbackChainOutputBody.
type GetFallbackChainOutputBody struct {
	Chain *[]FallbackChainEntryResponse `json:"chain"`
	Tiers *[]string                     `json:"tiers"`
}

// GetJobDebugCaptureOutputBody defines model for GetJobDebugCaptureOutputBody.
type GetJobDebugCaptureOutputBody struct {
	// ApiVersion API version that processed this job
	ApiVersion *string `json:"api_version,omitempty"`

	// Captures Captured LLM requests
	Captures *[]DebugCaptureEntry `json:"captures"`

	// Enabled Whether debug capture was enabled for this job
	Enabled bool `json:"enabled"`

	// IsByok Whether user's own API key was used
	IsByok *bool `json:"is_byok,omitempty"`

	// JobId Job ID
	JobId string `json:"job_id"`

	// JobType Job type (analyze, extract, crawl)
	JobType *string `json:"job_type,omitempty"`

	// TotalCostUsd Total cost in USD
	TotalCostUsd *float64 `json:"total_cost_usd,omitempty"`

	// TotalDurationMs Total duration in milliseconds
	TotalDurationMs *int64 `json:"total_duration_ms,omitempty"`

	// TotalRequests Number of LLM requests
	TotalRequests *int64 `json:"total_requests,omitempty"`

	// TotalTokensIn Total input tokens
	TotalTokensIn *int64 `json:"total_tokens_in,omitempty"`

	// TotalTokensOut Total output tokens
	TotalTokensOut *int64 `json:"total_tokens_out,omitempty"`
}

// GetJobResultsDownloadOutputBody defines model for GetJobResultsDownloadOutputBody.
type GetJobResultsDownloadOutputBody struct {
	// DownloadUrl Presigned URL to download results (valid for 1 hour)
	DownloadUrl string `json:"download_url"`

	// ExpiresAt URL expiration time
	ExpiresAt string `json:"expires_at"`

	// JobId Job ID
	JobId string `json:"job_id"`
}

// GetJobWebhookDeliveriesOutputBody defines model for GetJobWebhookDeliveriesOutputBody.
type GetJobWebhookDeliveriesOutputBody struct {
	// Deliveries Webhook deliveries for this job
	Deliveries *[]JobWebhookDeliveryResponse `json:"deliveries"`

	// JobId Job ID
	JobId string `json:"job_id"`
}

// GetTrendsOutputBody defines model for GetTrendsOutputBody.
type GetTrendsOutputBody struct {
	Trends *[]TrendPointResponse `json:"trends"`
}

// GetUsageOutputBody defines model for GetUsageOutputBody.
type GetUsageOutputBody struct {
	// ByokJobs Jobs using user's own API keys (not charged)
	ByokJobs int64 `json:"byok_jobs"`

	// TotalChargedUsd Total USD charged for usage
	TotalChargedUsd float64 `json:"total_charged_usd"`

	// TotalJobs Total number of jobs
	TotalJobs int64 `json:"total_jobs"`
}

// GetUserFallbackChainOutputBody defines model for GetUserFallbackChainOutputBody.
type GetUserFallbackChainOutputBody struct {
	Chain *[]UserFallbackChainEntryResponse `json:"chain"`
}

// HealthCheckOutputBody defines model for HealthCheckOutputBody.
type HealthCheckOutputBody struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// InlineWebhookInput defines model for InlineWebhookInput.
type InlineWebhookInput struct {
	// Events Event types to subscribe to (empty for all)
	Events *[]string `json:"events"`

	// Headers Custom headers
	Headers *[]WebhookHeaderInput `json:"headers"`

	// Secret Secret for HMAC-SHA256 signature
	Secret *string `json:"secret,omitempty"`

	// Url Webhook URL
	Url string `json:"url"`
}

// JobQueueStats defines model for JobQueueStats.
type JobQueueStats struct {
	// PendingByTier Pending jobs by tier
	PendingByTier map[string]int64 `json:"pending_by_tier"`

	// PendingTotal Total pending jobs
	PendingTotal int64 `json:"pending_total"`

	// RunningByTier Running jobs by tier
	RunningByTier map[string]int64 `json:"running_by_tier"`

	// RunningByUser Running jobs by user ID
	RunningByUser map[string]int64 `json:"running_by_user"`

	// RunningTotal Total running jobs
	RunningTotal int64 `json:"running_total"`
}

// JobResponse defines model for JobResponse.
type JobResponse struct {
	CaptureDebug     bool    `json:"capture_debug"`
	CompletedAt      *string `json:"completed_at,omitempty"`
	CostUsd          float64 `json:"cost_usd"`
	CreatedAt        string  `json:"created_at"`
	ErrorCategory    *string `json:"error_category,omitempty"`
	ErrorMessage     *string `json:"error_message,omitempty"`
	Id               string  `json:"id"`
	PageCount        int64   `json:"page_count"`
	QueuePosition    int64   `json:"queue_position"`
	StartedAt        *string `json:"started_at,omitempty"`
	Status           string  `json:"status"`
	TokenUsageInput  int64   `json:"token_usage_input"`
	TokenUsageOutput int64   `json:"token_usage_output"`
	Type             string  `json:"type"`
	Url              string  `json:"url"`
	UrlsQueued       int64   `json:"urls_queued"`
}

// JobWebhookDeliveryResponse defines model for JobWebhookDeliveryResponse.
type JobWebhookDeliveryResponse struct {
	// AttemptNumber Current attempt number
	AttemptNumber int64 `json:"attempt_number"`

	// CreatedAt Creation timestamp
	CreatedAt string `json:"created_at"`

	// DeliveredAt Successful delivery timestamp
	DeliveredAt *string `json:"delivered_at,omitempty"`

	// ErrorMessage Error message if failed
	ErrorMessage *string `json:"error_message,omitempty"`

	// EventType Event type that triggered this delivery
	EventType string `json:"event_type"`

	// Id Delivery ID
	Id string `json:"id"`

	// MaxAttempts Maximum retry attempts
	MaxAttempts int64 `json:"max_attempts"`

	// ResponseTimeMs Response time in milliseconds
	ResponseTimeMs *int64 `json:"response_time_ms,omitempty"`

	// Status Delivery status (pending, success, failed, retrying)
	Status string `json:"status"`

	// StatusCode HTTP status code received
	StatusCode *int64 `json:"status_code,omitempty"`

	// Url Destination URL
	Url string `json:"url"`

	// WebhookId Webhook ID (null for ephemeral)
	WebhookId *string `json:"webhook_id,omitempty"`
}

// LLMConfigInput defines model for LLMConfigInput.
type LLMConfigInput struct {
	// ApiKey API key for the provider
	ApiKey *string `json:"api_key,omitempty"`

	// BaseUrl Custom base URL (for Ollama or self-hosted Helicone)
	BaseUrl *string `json:"base_url,omitempty"`

	// Model Model to use
	Model *string `json:"model,omitempty"`

	// Provider LLM provider
	Provider *LLMConfigInputProvider `json:"provider,omitempty"`

	// TargetApiKey Underlying provider's API key for Helicone self-hosted mode
	TargetApiKey *string `json:"target_api_key,omitempty"`

	// TargetProvider Underlying provider for Helicone self-hosted mode
	TargetProvider *string `json:"target_provider,omitempty"`
}

// LLMConfigInputProvider LLM provider
type LLMConfigInputProvider string

// ListAllSchemasOutputBody defines model for ListAllSchemasOutputBody.
type ListAllSchemasOutputBody struct {
	// Schemas List of all schemas
	Schemas *[]SchemaOutput `json:"schemas"`
}

// ListCleanersOutputBody defines model for ListCleanersOutputBody.
type ListCleanersOutputBody struct {
	// Cleaners List of available cleaners
	Cleaners *[]CleanerResponse `json:"cleaners"`

	// DefaultAnalysisChain Default cleaner chain for analysis operations
	DefaultAnalysisChain *[]CleanerChainItemResponse `json:"default_analysis_chain"`

	// DefaultExtractionChain Default cleaner chain for extraction operations
	DefaultExtractionChain *[]CleanerChainItemResponse `json:"default_extraction_chain"`
}

// ListJobsOutputBody defines model for ListJobsOutputBody.
type ListJobsOutputBody struct {
	Jobs *[]JobResponse `json:"jobs"`
}

// ListKeysOutputBody defines model for ListKeysOutputBody.
type ListKeysOutputBody struct {
	Keys *[]APIKeyResponse `json:"keys"`
}

// ListModelsOutputBody defines model for ListModelsOutputBody.
type ListModelsOutputBody struct {
	Models *[]ProviderModelResponse `json:"models"`
}

// ListProvidersOutputBody defines model for ListProvidersOutputBody.
type ListProvidersOutputBody struct {
	Providers *[]ProviderInfo `json:"providers"`
}

// ListSavedSitesOutputBody defines model for ListSavedSitesOutputBody.
type ListSavedSitesOutputBody struct {
	// Sites List of saved sites
	Sites *[]SavedSiteOutput `json:"sites"`
}

// ListSchemasOutputBody defines model for ListSchemasOutputBody.
type ListSchemasOutputBody struct {
	// Schemas List of schemas
	Schemas *[]SchemaOutput `json:"schemas"`
}

// ListServiceKeysOutputBody defines model for ListServiceKeysOutputBody.
type ListServiceKeysOutputBody struct {
	Keys *[]ServiceKeyResponse `json:"keys"`
}

// ListTierLimitsOutputBody defines model for ListTierLimitsOutputBody.
type ListTierLimitsOutputBody struct {
	// Tiers List of visible tiers and their limits
	Tiers *[]TierLimitsResponse `json:"tiers"`
}

// ListTiersOutputBody defines model for ListTiersOutputBody.
type ListTiersOutputBody struct {
	Tiers *[]SubscriptionTierResponse `json:"tiers"`
}

// ListUserServiceKeysOutputBody defines model for ListUserServiceKeysOutputBody.
type ListUserServiceKeysOutputBody struct {
	Keys *[]UserServiceKeyResponse `json:"keys"`
}

// ListWebhookDeliveriesOutputBody defines model for ListWebhookDeliveriesOutputBody.
type ListWebhookDeliveriesOutputBody struct {
	// Deliveries List of webhook deliveries
	Deliveries *[]WebhookDeliveryResponse `json:"deliveries"`
}

// ListWebhooksOutputBody defines model for ListWebhooksOutputBody.
type ListWebhooksOutputBody struct {
	// Webhooks List of user's webhooks
	Webhooks *[]WebhookResponse `json:"webhooks"`
}

// LivezOutputBody defines model for LivezOutputBody.
type LivezOutputBody struct {
	// Status Liveness status
	Status string `json:"status"`
}

// MetadataResponse defines model for MetadataResponse.
type MetadataResponse struct {
	// ExtractDurationMs Time to extract data in milliseconds
	ExtractDurationMs int64 `json:"extract_duration_ms"`

	// FetchDurationMs Time to fetch the page in milliseconds
	FetchDurationMs int64 `json:"fetch_duration_ms"`

	// Model Model used for extraction
	Model string `json:"model"`

	// Provider LLM provider used
	Provider string `json:"provider"`
}

// ModelValidationRequest defines model for ModelValidationRequest.
type ModelValidationRequest struct {
	// Model Model identifier
	Model string `json:"model"`

	// Provider Provider name
	Provider string `json:"provider"`
}

// ModelValidationResponse defines model for ModelValidationResponse.
type ModelValidationResponse struct {
	Message  *string `json:"message,omitempty"`
	Model    string  `json:"model"`
	Provider string  `json:"provider"`
	Status   string  `json:"status"`
}

// OverviewResponse defines model for OverviewResponse.
type OverviewResponse struct {
	// ActiveUsers Number of unique users with jobs
	ActiveUsers int64 `json:"active_users"`

	// ByokJobs Jobs using user API keys
	ByokJobs int64 `json:"byok_jobs"`

	// CompletedJobs Number of completed jobs
	CompletedJobs int64 `json:"completed_jobs"`

	// ErrorRate Error rate percentage
	ErrorRate float64 `json:"error_rate"`

	// FailedJobs Number of failed jobs
	FailedJobs int64 `json:"failed_jobs"`

	// PlatformJobs Jobs using platform API keys
	PlatformJobs int64 `json:"platform_jobs"`

	// TotalCostUsd Total cost in USD
	TotalCostUsd float64 `json:"total_cost_usd"`

	// TotalJobs Total number of jobs
	TotalJobs int64 `json:"total_jobs"`

	// TotalTokensInput Total input tokens
	TotalTokensInput int64 `json:"total_tokens_input"`

	// TotalTokensOutput Total output tokens
	TotalTokensOutput int64 `json:"total_tokens_output"`
}

// ProviderErrorResponse defines model for ProviderErrorResponse.
type ProviderErrorResponse struct {
	Count    int64  `json:"count"`
	Model    string `json:"model"`
	Provider string `json:"provider"`
}

// ProviderInfo defines model for ProviderInfo.
type ProviderInfo struct {
	AllowBaseUrlOverride bool      `json:"allow_base_url_override"`
	BaseUrlHint          *string   `json:"base_url_hint,omitempty"`
	DecommissionNote     *string   `json:"decommission_note,omitempty"`
	Description          string    `json:"description"`
	DisplayName          string    `json:"display_name"`
	DocsUrl              *string   `json:"docs_url,omitempty"`
	KeyPlaceholder       *string   `json:"key_placeholder,omitempty"`
	Name                 string    `json:"name"`
	RequiredFeatures     *[]string `json:"required_features"`
	RequiresKey          bool      `json:"requires_key"`
	Status               string    `json:"status"`
	SuccessorProvider    *string   `json:"successor_provider,omitempty"`
}

// ProviderModelResponse defines model for ProviderModelResponse.
type ProviderModelResponse struct {
	ContextSize *int64  `json:"context_size,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	IsFree      bool    `json:"is_free"`
	Name        string  `json:"name"`
}

// RateLimitStats defines model for RateLimitStats.
type RateLimitStats struct {
	// ActiveSuspensions Number of currently suspended API keys
	ActiveSuspensions int64 `json:"active_suspensions"`

	// TotalEntries Total rate limit entries in database
	TotalEntries int64 `json:"total_entries"`
}

// ReadyzOutputBody defines model for ReadyzOutputBody.
type ReadyzOutputBody struct {
	// Status Readiness status
	Status string `json:"status"`
}

// RevokeKeyOutputBody defines model for RevokeKeyOutputBody.
type RevokeKeyOutputBody struct {
	Success bool `json:"success"`
}

// SSECompleteEvent defines model for SSECompleteEvent.
type SSECompleteEvent struct {
	// CostUsd Total cost in USD
	CostUsd *float64 `json:"cost_usd,omitempty"`

	// ErrorCategory Error category if job failed
	ErrorCategory *string `json:"error_category,omitempty"`

	// ErrorMessage Error message if job failed
	ErrorMessage *string `json:"error_message,omitempty"`

	// JobId Job ID
	JobId string `json:"job_id"`

	// PageCount Total pages processed
	PageCount int64 `json:"page_count"`

	// ResultsUrl URL to fetch full results
	ResultsUrl string `json:"results_url"`

	// Status Final job status
	Status string `json:"status"`
}

// SSEErrorEvent defines model for SSEErrorEvent.
type SSEErrorEvent struct {
	// Message Error message
	Message string `json:"message"`
}

// SSEResultEvent defines model for SSEResultEvent.
type SSEResultEvent struct {
	// ErrorCategory Error category if failed
	ErrorCategory *string `json:"error_category,omitempty"`

	// ErrorMessage Error message if failed
	ErrorMessage *string `json:"error_message,omitempty"`

	// Id Result ID
	Id string `json:"id"`

	// LlmModel LLM model used
	LlmModel *string `json:"llm_model,omitempty"`

	// LlmProvider LLM provider used
	LlmProvider *string `json:"llm_provider,omitempty"`

	// Status Crawl status (pending, completed, failed)
	Status string `json:"status"`

	// Url Source URL
	Url string `json:"url"`
}

// SSEStatusEvent defines model for SSEStatusEvent.
type SSEStatusEvent struct {
	// JobId Job ID
	JobId string `json:"job_id"`

	// PageCount Number of pages processed so far
	PageCount int64 `json:"page_count"`

	// Status Job status (pending, running, completed, failed)
	Status string `json:"status"`

	// UrlsQueued Number of URLs queued for processing
	UrlsQueued int64 `json:"urls_queued"`
}

// SavedSiteOutput defines model for SavedSiteOutput.
type SavedSiteOutput struct {
	AnalysisResult *AnalysisResultOutput `json:"analysis_result,omitempty"`
	CrawlOptions   *CrawlOptionsOutput   `json:"crawl_options,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt string `json:"created_at"`

	// DefaultSchemaId Default schema to use
	DefaultSchemaId *string `json:"default_schema_id,omitempty"`

	// Domain Extracted domain
	Domain string `json:"domain"`

	// FetchMode Fetch mode: auto, static, dynamic
	FetchMode string `json:"fetch_mode"`

	// Id Site ID
	Id string `json:"id"`

	// Name User-friendly name
	Name *string `json:"name,omitempty"`

	// OrganizationId Organization ID for sharing
	OrganizationId *string `json:"organization_id,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt string `json:"updated_at"`

	// Url Site URL
	Url string `json:"url"`

	// UserId Owner user ID
	UserId string `json:"user_id"`
}

// SchemaOutput defines model for SchemaOutput.
type SchemaOutput struct {
	// Category Schema category
	Category *string `json:"category,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt string `json:"created_at"`

	// Description Schema description
	Description *string `json:"description,omitempty"`

	// Id Schema ID
	Id string `json:"id"`

	// IsPlatform True for admin-managed schemas
	IsPlatform bool `json:"is_platform"`

	// Name Schema name
	Name string `json:"name"`

	// OrganizationId Organization ID (Clerk)
	OrganizationId *string `json:"organization_id,omitempty"`

	// SchemaYaml YAML schema content
	SchemaYaml string `json:"schema_yaml"`

	// Tags Schema tags
	Tags *[]string `json:"tags"`

	// UpdatedAt Last update timestamp
	UpdatedAt string `json:"updated_at"`

	// UsageCount Number of times schema has been used
	UsageCount int64 `json:"usage_count"`

	// UserId Creator user ID
	UserId *string `json:"user_id,omitempty"`

	// Visibility Visibility: platform, public, private
	Visibility string `json:"visibility"`
}

// ServiceKeyInput defines model for ServiceKeyInput.
type ServiceKeyInput struct {
	// ApiKey API key for the provider (required for new keys, optional for updates)
	ApiKey *string `json:"api_key,omitempty"`

	// IsEnabled Whether this provider is enabled
	IsEnabled bool `json:"is_enabled"`

	// Provider LLM provider name (see /llm/providers for available options)
	Provider string `json:"provider"`
}

// ServiceKeyResponse defines model for ServiceKeyResponse.
type ServiceKeyResponse struct {
	CreatedAt string `json:"created_at"`
	HasKey    bool   `json:"has_key"`
	IsEnabled bool   `json:"is_enabled"`
	Provider  string `json:"provider"`
	UpdatedAt string `json:"updated_at"`
}

// SetFallbackChainInputBody defines model for SetFallbackChainInputBody.
type SetFallbackChainInputBody struct {
	// Chain Ordered list of provider:model pairs
	Chain *[]FallbackChainEntryInput `json:"chain"`

	// Tier Tier to set chain for (null for default chain)
	Tier *string `json:"tier,omitempty"`
}

// SetFallbackChainOutputBody defines model for SetFallbackChainOutputBody.
type SetFallbackChainOutputBody struct {
	Chain *[]FallbackChainEntryResponse `json:"chain"`
}

// SetUserFallbackChainInputBody defines model for SetUserFallbackChainInputBody.
type SetUserFallbackChainInputBody struct {
	// Chain Ordered list of provider:model pairs
	Chain *[]UserFallbackChainEntryInput `json:"chain"`
}

// SetUserFallbackChainOutputBody defines model for SetUserFallbackChainOutputBody.
type SetUserFallbackChainOutputBody struct {
	Chain *[]UserFallbackChainEntryResponse `json:"chain"`
}

// SubscriptionTierResponse defines model for SubscriptionTierResponse.
type SubscriptionTierResponse struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	IsDefault   bool    `json:"is_default"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// SyncTiersOutputBody defines model for SyncTiersOutputBody.
type SyncTiersOutputBody struct {
	// Message Sync result message
	Message string `json:"message"`
}

// SystemMetrics defines model for SystemMetrics.
type SystemMetrics struct {
	JobQueue   JobQueueStats  `json:"job_queue"`
	RateLimits RateLimitStats `json:"rate_limits"`
}

// TierLimitsResponse defines model for TierLimitsResponse.
type TierLimitsResponse struct {
	// CreditAllocationUsd Monthly USD credit for premium model calls (0 = none)
	CreditAllocationUsd float64 `json:"credit_allocation_usd"`

	// CreditRolloverMonths Credit expiry: -1 = never, 0 = current period, N = N additional periods
	CreditRolloverMonths int64 `json:"credit_rollover_months"`

	// DisplayName Human-readable tier name (from Clerk Commerce)
	DisplayName string `json:"display_name"`

	// MaxConcurrentJobs Max concurrent jobs (0 = unlimited)
	MaxConcurrentJobs int64 `json:"max_concurrent_jobs"`

	// MaxPagesPerCrawl Max pages per crawl job (0 = unlimited)
	MaxPagesPerCrawl int64 `json:"max_pages_per_crawl"`

	// MonthlyExtractions Monthly extraction limit (0 = unlimited)
	MonthlyExtractions int64 `json:"monthly_extractions"`

	// Name Tier name (free, standard, pro, selfhosted)
	Name string `json:"name"`

	// RequestsPerMinute API requests per minute limit (0 = unlimited)
	RequestsPerMinute int64 `json:"requests_per_minute"`
}

// TierValidationRequest defines model for TierValidationRequest.
type TierValidationRequest struct {
	// TierId Tier ID or slug to validate
	TierId string `json:"tier_id"`
}

// TierValidationResponse defines model for TierValidationResponse.
type TierValidationResponse struct {
	CurrentSlug *string `json:"current_slug,omitempty"`
	Message     *string `json:"message,omitempty"`
	Status      string  `json:"status"`
	TierId      string  `json:"tier_id"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	// Input Total input tokens consumed across all extractions
	Input int64 `json:"input"`

	// Output Total output tokens generated across all extractions
	Output int64 `json:"output"`
}

// TrendPointResponse defines model for TrendPointResponse.
type TrendPointResponse struct {
	CostUsd    float64 `json:"cost_usd"`
	Date       string  `json:"date"`
	ErrorCount int64   `json:"error_count"`
	JobCount   int64   `json:"job_count"`
	Tokens     int64   `json:"tokens"`
}

// UpdateSavedSiteInputBody defines model for UpdateSavedSiteInputBody.
type UpdateSavedSiteInputBody struct {
	AnalysisResult *AnalysisResultInput `json:"analysis_result,omitempty"`
	CrawlOptions   *CrawlOptionsInput   `json:"crawl_options,omitempty"`

	// DefaultSchemaId Default schema ID
	DefaultSchemaId *string `json:"default_schema_id,omitempty"`

	// FetchMode Fetch mode
	FetchMode *UpdateSavedSiteInputBodyFetchMode `json:"fetch_mode,omitempty"`

	// Name User-friendly name
	Name *string `json:"name,omitempty"`

	// Url Site URL (ignored on update)
	Url *string `json:"url,omitempty"`
}

// UpdateSavedSiteInputBodyFetchMode Fetch mode
type UpdateSavedSiteInputBodyFetchMode string

// UpdateSchemaInputBody defines model for UpdateSchemaInputBody.
type UpdateSchemaInputBody struct {
	// Category Schema category
	Category *string `json:"category,omitempty"`

	// Description Schema description
	Description *string `json:"description,omitempty"`

	// Name Schema name
	Name *string `json:"name,omitempty"`

	// SchemaYaml YAML schema content
	SchemaYaml *string `json:"schema_yaml,omitempty"`

	// Tags Schema tags
	Tags *[]string `json:"tags"`

	// Visibility Schema visibility
	Visibility *UpdateSchemaInputBodyVisibility `json:"visibility,omitempty"`
}

// UpdateSchemaInputBodyVisibility Schema visibility
type UpdateSchemaInputBodyVisibility string

// UsageResponse defines model for UsageResponse.
type UsageResponse struct {
	// CostUsd Total USD cost charged for this extraction
	CostUsd float64 `json:"cost_usd"`

	// InputTokens Number of input tokens used
	InputTokens int64 `json:"input_tokens"`

	// IsByok True if user's own API key was used (no charge)
	IsByok bool `json:"is_byok"`

	// LlmCostUsd Actual LLM cost from provider
	LlmCostUsd float64 `json:"llm_cost_usd"`

	// OutputTokens Number of output tokens used
	OutputTokens int64 `json:"output_tokens"`
}

// UserFallbackChainEntryInput defines model for UserFallbackChainEntryInput.
type UserFallbackChainEntryInput struct {
	// IsEnabled Whether this entry is enabled
	IsEnabled bool `json:"is_enabled"`

	// MaxTokens Max output tokens (nil for default)
	MaxTokens *int64 `json:"max_tokens,omitempty"`

	// Model Model identifier
	Model string `json:"model"`

	// Provider LLM provider name (see /llm/providers for available options)
	Provider string `json:"provider"`

	// Temperature Temperature setting (0.0-1.0, nil for default)
	Temperature *float64 `json:"temperature,omitempty"`
}

// UserFallbackChainEntryResponse defines model for UserFallbackChainEntryResponse.
type UserFallbackChainEntryResponse struct {
	CreatedAt   string   `json:"created_at"`
	Id          string   `json:"id"`
	IsEnabled   bool     `json:"is_enabled"`
	MaxTokens   *int64   `json:"max_tokens,omitempty"`
	Model       string   `json:"model"`
	Position    int64    `json:"position"`
	Provider    string   `json:"provider"`
	Temperature *float64 `json:"temperature,omitempty"`
	UpdatedAt   string   `json:"updated_at"`
}

// UserListModelsOutputBody defines model for UserListModelsOutputBody.
type UserListModelsOutputBody struct {
	Models *[]UserModelResponse `json:"models"`
}

// UserModelResponse defines model for UserModelResponse.
type UserModelResponse struct {
	ContextSize *int64  `json:"context_size,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	IsFree      bool    `json:"is_free"`
	Name        string  `json:"name"`
}

// UserServiceKeyInput defines model for UserServiceKeyInput.
type UserServiceKeyInput struct {
	// ApiKey API key for the provider (leave empty to keep existing)
	ApiKey *string `json:"api_key,omitempty"`

	// BaseUrl Base URL for the provider (for Ollama or custom endpoints)
	BaseUrl *string `json:"base_url,omitempty"`

	// IsEnabled Whether this provider is enabled
	IsEnabled bool `json:"is_enabled"`

	// Provider LLM provider name (see /llm/providers for available options)
	Provider string `json:"provider"`
}

// UserServiceKeyResponse defines model for UserServiceKeyResponse.
type UserServiceKeyResponse struct {
	BaseUrl   *string `json:"base_url,omitempty"`
	CreatedAt string  `json:"created_at"`
	HasKey    bool    `json:"has_key"`
	Id        string  `json:"id"`
	IsEnabled bool    `json:"is_enabled"`
	Provider  string  `json:"provider"`
	UpdatedAt string  `json:"updated_at"`
}

// UserSummaryResponse defines model for UserSummaryResponse.
type UserSummaryResponse struct {
	CompletedJobs int64   `json:"completed_jobs"`
	FailedJobs    int64   `json:"failed_jobs"`
	LastActive    *string `json:"last_active,omitempty"`
	TotalCostUsd  float64 `json:"total_cost_usd"`
	TotalJobs     int64   `json:"total_jobs"`
	TotalTokens   int64   `json:"total_tokens"`
	UserId        string  `json:"user_id"`
}

// ValidateModelsInputBody defines model for ValidateModelsInputBody.
type ValidateModelsInputBody struct {
	// Models Models to validate
	Models *[]ModelValidationRequest `json:"models"`
}

// ValidateModelsOutputBody defines model for ValidateModelsOutputBody.
type ValidateModelsOutputBody struct {
	Results *[]ModelValidationResponse `json:"results"`
}

// ValidateTiersInputBody defines model for ValidateTiersInputBody.
type ValidateTiersInputBody struct {
	// Tiers Tiers to validate
	Tiers *[]TierValidationRequest `json:"tiers"`
}

// ValidateTiersOutputBody defines model for ValidateTiersOutputBody.
type ValidateTiersOutputBody struct {
	Results *[]TierValidationResponse `json:"results"`
}

// WebhookDeliveryResponse defines model for WebhookDeliveryResponse.
type WebhookDeliveryResponse struct {
	// AttemptNumber Current attempt number
	AttemptNumber int64 `json:"attempt_number"`

	// CreatedAt Creation timestamp
	CreatedAt string `json:"created_at"`

	// DeliveredAt Successful delivery timestamp
	DeliveredAt *string `json:"delivered_at,omitempty"`

	// ErrorMessage Error message if failed
	ErrorMessage *string `json:"error_message,omitempty"`

	// EventType Event type that triggered this delivery
	EventType string `json:"event_type"`

	// Id Delivery ID
	Id string `json:"id"`

	// JobId Associated job ID
	JobId string `json:"job_id"`

	// MaxAttempts Maximum retry attempts
	MaxAttempts int64 `json:"max_attempts"`

	// NextRetryAt Next retry time if retrying
	NextRetryAt *string `json:"next_retry_at,omitempty"`

	// ResponseTimeMs Response time in milliseconds
	ResponseTimeMs *int64 `json:"response_time_ms,omitempty"`

	// Status Delivery status (pending, success, failed, retrying)
	Status string `json:"status"`

	// StatusCode HTTP status code received
	StatusCode *int64 `json:"status_code,omitempty"`

	// Url Destination URL
	Url string `json:"url"`

	// WebhookId Webhook ID (null for ephemeral webhooks)
	WebhookId *string `json:"webhook_id,omitempty"`
}

// WebhookHeaderInput defines model for WebhookHeaderInput.
type WebhookHeaderInput struct {
	// Name Header name
	Name string `json:"name"`

	// Value Header value
	Value string `json:"value"`
}

// WebhookInput defines model for WebhookInput.
type WebhookInput struct {
	// Events Event types to subscribe to (empty or ["*"] for all events)
	Events *[]string `json:"events"`

	// Headers Custom headers to include in webhook requests
	Headers *[]WebhookHeaderInput `json:"headers"`

	// IsActive Whether this webhook is active
	IsActive bool `json:"is_active"`

	// Name Unique name for this webhook
	Name string `json:"name"`

	// Secret Secret for HMAC-SHA256 signature (leave empty to disable signing)
	Secret *string `json:"secret,omitempty"`

	// Url Webhook URL to send events to
	Url string `json:"url"`
}

// WebhookResponse defines model for WebhookResponse.
type WebhookResponse struct {
	// CreatedAt Creation timestamp
	CreatedAt string `json:"created_at"`

	// Events Subscribed event types
	Events *[]string `json:"events"`

	// HasSecret Whether this webhook has a secret configured
	HasSecret bool `json:"has_secret"`

	// Headers Custom headers
	Headers *[]WebhookHeaderInput `json:"headers"`

	// Id Unique webhook ID
	Id string `json:"id"`

	// IsActive Whether this webhook is active
	IsActive bool `json:"is_active"`

	// Name Webhook name
	Name string `json:"name"`

	// UpdatedAt Last update timestamp
	UpdatedAt string `json:"updated_at"`

	// Url Webhook URL
	Url string `json:"url"`
}

// CrawlParams defines parameters for Crawl.
type CrawlParams struct {
	// Wait Block until job completes and return results directly. Max wait time is 2 minutes. Returns 202 if timeout exceeded.
	Wait *bool `form:"wait,omitempty" json:"wait,omitempty"`

	// Timeout Maximum seconds to wait when wait=true (default 120s, max 120s/2min). For longer jobs, use async mode.
	Timeout *int64 `form:"timeout,omitempty" json:"timeout,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// Limit Number of jobs to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetJobResultsRawParams defines parameters for GetJobResultsRaw.
type GetJobResultsRawParams struct {
	// Merge Merge all page results into single array
	Merge *bool `form:"merge,omitempty" json:"merge,omitempty"`

	// Format Output format override
	Format *GetJobResultsRawParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetJobResultsRawParamsFormat defines parameters for GetJobResultsRaw.
type GetJobResultsRawParamsFormat string

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	// IncludeDecommissioned Include decommissioned providers in the response
	IncludeDecommissioned *bool `form:"include_decommissioned,omitempty" json:"include_decommissioned,omitempty"`
}

// ListSchemasParams defines parameters for ListSchemas.
type ListSchemasParams struct {
	// Category Filter by category
	Category *string `form:"category,omitempty" json:"category,omitempty"`

	// IncludePublic Include public schemas
	IncludePublic *bool `form:"include_public,omitempty" json:"include_public,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	// Period Time period for usage summary
	Period *GetUsageParamsPeriod `form:"period,omitempty" json:"period,omitempty"`
}

// GetUsageParamsPeriod defines parameters for GetUsage.
type GetUsageParamsPeriod string

// ListWebhookDeliveriesParams defines parameters for ListWebhookDeliveries.
type ListWebhookDeliveriesParams struct {
	// Limit Maximum number of deliveries to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of deliveries to skip
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// AnalyzeJSONRequestBody defines body for Analyze for application/json ContentType.
type AnalyzeJSONRequestBody = AnalyzeInputBody

// CrawlJSONRequestBody defines body for Crawl for application/json ContentType.
type CrawlJSONRequestBody = CreateCrawlJobInputBody

// ExtractJSONRequestBody defines body for Extract for application/json ContentType.
type ExtractJSONRequestBody = ExtractInputBody

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateKeyInputBody

// SetLlmChainJSONRequestBody defines body for SetLlmChain for application/json ContentType.
type SetLlmChainJSONRequestBody = SetUserFallbackChainInputBody

// UpsertLlmKeyJSONRequestBody defines body for UpsertLlmKey for application/json ContentType.
type UpsertLlmKeyJSONRequestBody = UserServiceKeyInput

// CreateSchemaJSONRequestBody defines body for CreateSchema for application/json ContentType.
type CreateSchemaJSONRequestBody = CreateSchemaInputBody

// UpdateSchemaJSONRequestBody defines body for UpdateSchema for application/json ContentType.
type UpdateSchemaJSONRequestBody = UpdateSchemaInputBody

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSavedSiteInputBody

// UpdateSiteJSONRequestBody defines body for UpdateSite for application/json ContentType.
type UpdateSiteJSONRequestBody = UpdateSavedSiteInputBody

// CreateWebhookJSONRequestBody defines body for CreateWebhook for application/json ContentType.
type CreateWebhookJSONRequestBody = WebhookInput

// UpdateWebhookJSONRequestBody defines body for UpdateWebhook for application/json ContentType.
type UpdateWebhookJSONRequestBody = WebhookInput
